name: SaltyGamesAPI
main: main.java.me.aaron.saltygamesapi
version: 1.0
author: [Aaron, TheSaltyOne, Sistogy]
softdepend: [Vault]
commands:
   mapi:
      description: Main Command
      usage: /mapi [action]
      aliases: [mgapi, mglib]
   party:
      description: Main Party Command
      usage: /party [action]
   start:
      description: Start Kuerzel
      usage: /start [action]
      aliases: [startmg, startminigame]